#!/bin/bash
echo "======================================"
echo "DeepSeek Chat Client 演示"
echo "======================================"
echo ""
echo "项目位置：/workspace/deepseek-chat"
echo ""
echo "文件结构:"
find deepseek-chat -type f | sort
echo ""
echo "======================================"
echo "编译状态：已完成 ✓"
echo "======================================"
echo ""
echo "运行方法:"
echo "  cd /workspace/deepseek-chat"
echo "  ./run.sh"
echo ""
echo "或者:"
echo "  java -cp /workspace/deepseek-chat/out DeepSeekChatClient"
echo ""
